### ISSUE TITLE
flac fuzz target finds panic very fast

### ISSUE THREAD

**Issue by frewsxcv** [rust-fuzz/targets#21]
Similar to https://github.com/rust-fuzz/targets/issues/14

**Comment by alex** [comment]
Here's a minimized input that panics:

```
root@266ef684c7e2:/targets# xxd ./minimized-from-8202682ef58ff49567f642bf4c59a090b0330fba
0000000: 664c 6143 0100 0000                      fLaC....
```

**Comment by frewsxcv** [comment]
Bug filed: https://github.com/sourrust/flac/issues/11

Trophy added: https://github.com/rust-fuzz/cargo-fuzz/pull/82
