### ISSUE TITLE
add fuzz target for rustfmt

### ISSUE THREAD

**Issue by frewsxcv** [rust-fuzz/targets#24]
https://github.com/rust-lang-nursery/rustfmt/blob/c9ac3487595eb56339d57de33aa326ac9e762f9c/src/lib.rs#L638

**Comment by frewsxcv** [comment]
relevant discussion https://github.com/rust-lang-nursery/rustfmt/issues/1344#issuecomment-283056957

**Comment by killercup** [comment]
I have a trivial script working, but it crashes after <1s with

```
thread '<unnamed>' panicked at 'Box<Any>', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.58.1/src/parse/lexer/mod.rs:182
```

which is not a rustfmt thing but a panic from libsyntax (or, syntex_syntax in this case)… that line is literally `panic!(FatalError);`! With a seed folder (cf. #41) made from

```sh
$ mkdir -pv rustfmt/seeds
$ cp **/*.rs rustfmt/seeds/
```

I get to 38 execs (the seed files) covering 12550 code paths, but the first new one leads to a libsytax crash.

I assume rustfmt should catch libsyntax panics? There is also a bunch of diagnostics output from libsyntax I can't get rid of.

I can open a PR later if you'd rather want to discuss this there.

**Comment by frewsxcv** [comment]
Cool! I've been meaning to do this. Feel free to open a PR. I'll merge it in, even if it immediately fails upon running. Do you have a backtrace of the panic?

**Comment by killercup** [comment]
@frewsxcv opened #42. I don't have the logs anymore, but it's easy to reproduce.

**Comment by killercup** [comment]
Logs! https://gist.github.com/killercup/406457100de570a33dfd68192ea0e9ee

**Comment by frewsxcv** [comment]
Maybe we should add a fuzz target for https://github.com/serde-rs/syntex and report this panic upstream?

**Comment by frewsxcv** [comment]
Regardless, this was completed in https://github.com/rust-fuzz/targets/issues/42. Thanks again!
