### ISSUE TITLE
add fuzz target for 'image' crate

### ISSUE THREAD

**Issue by frewsxcv** [rust-fuzz/targets#26]
https://github.com/PistonDevelopers/image

there are multiple formats it can read, so we'll probably want a different fuzz target for each format. those can be separate PRs

**Comment by killercup** [comment]
Maybe it's better to fuzz the underlying libraries where possible? https://github.com/PistonDevelopers/image/blob/59cf88a704bf13e0e2d7c02003ed2e54f7e6c9bb/Cargo.toml#L31-L41
