### ISSUE TITLE
add fuzz target for syntex_syntax

### ISSUE THREAD

**Issue by frewsxcv** [rust-fuzz/targets#44]
https://github.com/rust-fuzz/targets/issues/24

https://github.com/serde-rs/syntex

https://docs.rs/syntex_syntax/

**Comment by frewsxcv** [comment]
Though, it looks like the future of syntex is unknown https://github.com/serde-rs/syntex/issues/114

**Comment by dtolnay** [comment]
I would recommend not bothering with this.
