### ISSUE TITLE
Add targets for 'http' crate

### ISSUE THREAD

**Issue by frewsxcv** [rust-fuzz/targets#88]
https://github.com/carllerche/http/blob/e349ecb85084d3295c0bb55766cf599188f41de5/tests/header_map_fuzz.rs

**Comment by frewsxcv** [comment]
`http` just had it's 1.0 release

I threw together a fuzz target for `StatusCode`:

```rust
#![no_main]
#[macro_use] extern crate libfuzzer_sys;
extern crate http;

fuzz_target!(|data: &[u8]| {
    if let Ok(status_code) = http::status::StatusCode::from_bytes(data) {
        status_code.is_informational();
        status_code.is_success();
        status_code.is_redirection();
        status_code.is_client_error();
        status_code.is_server_error();
        status_code.to_string();
        let s = status_code.as_str();
        format!("{:?}", status_code);
        assert_eq!(
            status_code,
            http::status::StatusCode::from_bytes(s.as_bytes()).unwrap()
        );
    }
});
```

**Comment by killercup** [comment]
I think you meant 0.1 :)

The crate has [a few](https://docs.rs/http/0.1.0/http/header/struct.HeaderName.html?search=from_bytes) of `from_bytes` methods. Do you want to add fuzzers for all of them?

**Comment by frewsxcv** [comment]
yeah, seems appropriate to add fuzz targets for each of those, though i don't think there's too much nuanced logic in the 'http' crate that would catch any bugs, but you never know!

**Comment by killercup** [comment]
You know how the saying goes: Better be fuzzy than sorry

Corey Farwell <notifications@github.com> schrieb am So. 10. Sep. 2017 um
20:19:
