### ISSUE TITLE
fuzz minidump crate

### ISSUE THREAD

**Issue by frewsxcv** [rust-fuzz/targets#94]
https://twitter.com/TedMielczarek/status/943922075428941830

I saw the word 'parser' and the fuzzing portion of my brain lit up

**Comment by Manishearth** [comment]
cc @luser

**Comment by luser** [comment]
A solid plan. :) The parser itself is probably not the best code, I was pretty new at Rust when I wrote most of it.

**Comment by luser** [comment]
There's a [`Minidump::read`](https://docs.rs/minidump/0.1.0/minidump/struct.Minidump.html#method.read) method that takes anything that implements `Read + Seek`, so it's pretty easy to stick bytes in a `Cursor` and parse it. Note that it doesn't parse the whole file with that, just the header and the stream directory. You can call [`Minidump::get_stream`](https://docs.rs/minidump/0.1.0/minidump/struct.Minidump.html#method.get_stream) with individual stream types to get them to parse.

**Comment by frewsxcv** [comment]
i threw together a fuzz target:

```rust
#![no_main]

#[macro_use] extern crate libfuzzer_sys;
extern crate minidump;

use minidump::Minidump;
use std::io::Cursor;

fuzz_target!(|data: &[u8]| {
    let cursor = Cursor::new(data);
    minidump::Minidump::read(cursor);
});
```

though it currently doesn't compile because `Minidump::read` requires `'static` on the single argument. any reason why this needs a static lifetime?

**Comment by frewsxcv** [comment]
opened a github issue with a couple associated pull requests: https://github.com/luser/rust-minidump/issues/6
